-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgUkAIEIauYQDGmOgg
S2z75MCdc/wFjL2uGRSIOv4T1HegCgYIKoZIzj0DAQehRANCAAQugJ2idOzqY4qj
DXnLu23e7qJCjpdpenkQ117aT6WcEato7SOsKMypGcPWHKjQJGw9WzOaj8dcl4LK
oLvdx9Tw
-----END PRIVATE KEY-----